# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

select_list_impl <- function(l, vars) {
    .Call('_select4lists_select_list_impl', PACKAGE = 'select4lists', l, vars)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_select4lists_RcppExport_registerCCallable', PACKAGE = 'select4lists')
})
